"""Helpers for model identifier fields in FastAPI generation."""

from __future__ import annotations

from microforge.domain.spec.models import FieldSpec, ModelSpec
from microforge.domain.spec.types import FieldType


def id_field_for(model: ModelSpec) -> FieldSpec | None:
    """Return the model id field when present."""

    return next((field for field in model.fields if field.name == "id"), None)


def id_is_uuid(model: ModelSpec) -> bool:
    """Return whether the model id is a UUID generated by the API mapper."""

    id_field = id_field_for(model)
    return id_field is not None and id_field.type == FieldType.uuid
