"""FastAPI project generator adapter."""

from __future__ import annotations

import json
import re

from microforge.application.generation.ports.outbound import ProjectGeneratorPort
from microforge.domain.generation.project_file import ProjectFile
from microforge.domain.spec.models import SpecV1


class FastApiProjectGenerator(ProjectGeneratorPort):
    """Generate a minimal FastAPI project from a spec."""

    def generate(self, spec: SpecV1) -> list[ProjectFile]:
        package_name = _to_package_name(spec.service.name)
        return [
            ProjectFile(
                path="README.md",
                content=_encode(_render_readme(spec)),
            ),
            ProjectFile(
                path="pyproject.toml",
                content=_encode(_render_pyproject(spec, package_name)),
            ),
            ProjectFile(
                path="src/main.py",
                content=_encode(_render_main(spec)),
            ),
        ]


def _to_package_name(service_name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]+", "_", service_name.strip().lower())
    normalized = normalized.strip("_")
    return normalized or "generated_service"


def _render_readme(spec: SpecV1) -> str:
    description = spec.service.description or "Generated FastAPI service."
    return f"""# {spec.service.name}

{description}

Generated by microforge.
"""


def _render_pyproject(spec: SpecV1, package_name: str) -> str:
    description = spec.service.description or "Generated FastAPI service"
    return f"""[project]
name = {_quote(package_name)}
version = "0.1.0"
description = {_quote(description)}
requires-python = {_quote(f">={spec.target.python_version}")}
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
]
"""


def _render_main(spec: SpecV1) -> str:
    return f'''from fastapi import FastAPI

app = FastAPI(title={_quote(f"{spec.service.name} API")})


@app.get("{spec.api.base_path}/health")
def health() -> dict[str, str]:
    return {{"status": "ok"}}
'''


def _encode(content: str) -> bytes:
    return content.encode("utf-8")


def _quote(value: str) -> str:
    return json.dumps(value)
