import pathlib
import zipfile
from io import BytesIO

from fastapi import FastAPI
from fastapi.testclient import TestClient

from microforge.infrastructure.inbound.api.v1.routes import router

app = FastAPI(title="microforge API")
app.include_router(router, prefix="/api/v1")


def _read_bytes(path: str) -> bytes:
    return pathlib.Path(path).read_bytes()


def test_health_endpoint() -> None:
    client = TestClient(app)
    response = client.get("/api/v1/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_validate_accepts_valid_yaml() -> None:
    client = TestClient(app)
    response = client.post(
        "/api/v1/spec/validate",
        files={
            "file": ("spec_valid.yaml", _read_bytes("examples/spec_valid.yaml"), "application/yaml")
        },
    )
    assert response.status_code == 200
    assert response.json() == {"ok": True}


def test_validate_rejects_invalid_extension() -> None:
    client = TestClient(app)
    response = client.post(
        "/api/v1/spec/validate",
        files={"file": ("spec.txt", b"specVersion: 1", "text/plain")},
    )
    assert response.status_code == 400
    assert response.json()["detail"] == "Only .yaml/.yml files are accepted"


def test_validate_returns_all_semantic_errors() -> None:
    client = TestClient(app)
    response = client.post(
        "/api/v1/spec/validate",
        files={
            "file": (
                "spec_invalid.yaml",
                _read_bytes("examples/spec_invalid.yaml"),
                "application/yaml",
            )
        },
    )
    assert response.status_code == 400
    detail = response.json()["detail"]
    assert isinstance(detail, list)
    assert len(detail) == 2
    assert all(item["model"] == "Order" for item in detail)


def test_validate_rejects_invalid_structure() -> None:
    client = TestClient(app)
    response = client.post(
        "/api/v1/spec/validate",
        files={"file": ("empty.yaml", b"[]", "application/yaml")},
    )
    assert response.status_code == 400
    assert "Invalid spec structure" in response.json()["detail"]


def test_generate_project_returns_zip() -> None:
    client = TestClient(app)
    response = client.post(
        "/api/v1/spec/generate",
        files={
            "file": ("spec_valid.yaml", _read_bytes("examples/spec_valid.yaml"), "application/yaml")
        },
    )

    assert response.status_code == 200
    assert response.headers["content-type"] == "application/zip"
    assert response.headers["content-disposition"] == 'attachment; filename="spec_valid.zip"'

    with zipfile.ZipFile(BytesIO(response.content)) as archive:
        assert sorted(archive.namelist()) == [
            "README.md",
            "pyproject.toml",
            "src/orders_service/application/ports/repositories/__init__.py",
            "src/orders_service/application/ports/repositories/order_repository.py",
            "src/orders_service/application/use_cases/__init__.py",
            "src/orders_service/application/use_cases/order/__init__.py",
            "src/orders_service/application/use_cases/order/find_orders_by_status.py",
            "src/orders_service/application/use_cases/order/list_orders.py",
            "src/orders_service/domain/models/__init__.py",
            "src/orders_service/domain/models/order.py",
            "src/orders_service/infrastructure/inbound/api/providers.py",
            "src/orders_service/infrastructure/inbound/api/routes/__init__.py",
            "src/orders_service/infrastructure/inbound/api/routes/order_routes.py",
            "src/orders_service/infrastructure/inbound/api/schemas/__init__.py",
            "src/orders_service/infrastructure/inbound/api/schemas/order/__init__.py",
            "src/orders_service/infrastructure/inbound/api/schemas/order/order_read.py",
            "src/orders_service/infrastructure/persistence/__init__.py",
            "src/orders_service/infrastructure/persistence/base.py",
            "src/orders_service/infrastructure/persistence/order.py",
            "src/orders_service/infrastructure/persistence/repositories/__init__.py",
            "src/orders_service/infrastructure/persistence/repositories/order_repository.py",
            "src/orders_service/infrastructure/persistence/session.py",
            "src/orders_service/main.py",
        ]
        assert b"Generated by microforge" in archive.read("README.md")
        assert b"class OrderRepositoryPort(Protocol):" in archive.read(
            "src/orders_service/application/ports/repositories/order_repository.py"
        )
        assert b"class ListOrdersUseCase:" in archive.read(
            "src/orders_service/application/use_cases/order/list_orders.py"
        )
        assert b'router = APIRouter(prefix="/orders", tags=["orders"])' in archive.read(
            "src/orders_service/infrastructure/inbound/api/routes/order_routes.py"
        )
        assert b"class Order:" in archive.read("src/orders_service/domain/models/order.py")
        order_schema = archive.read(
            "src/orders_service/infrastructure/inbound/api/schemas/order/order_read.py"
        )
        assert b"class OrderRead(BaseModel):" in order_schema
        assert b"class OrderCreate(BaseModel):" not in order_schema
        assert b"class OrderORM(Base):" in archive.read(
            "src/orders_service/infrastructure/persistence/order.py"
        )
        assert b"class SqlAlchemyOrderRepository(OrderRepositoryPort):" in archive.read(
            "src/orders_service/infrastructure/persistence/repositories/order_repository.py"
        )


def test_generate_project_returns_semantic_errors() -> None:
    client = TestClient(app)
    response = client.post(
        "/api/v1/spec/generate",
        files={
            "file": (
                "spec_invalid.yaml",
                _read_bytes("examples/spec_invalid.yaml"),
                "application/yaml",
            )
        },
    )

    assert response.status_code == 400
    detail = response.json()["detail"]
    assert isinstance(detail, list)
    assert len(detail) == 2
